import { Open_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import PropTypes from 'prop-types'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import './globals.css'

export const metadata = {
    title: 'Next EDSoft',
    description: 'Generated by create next app'
}

const openSans = Open_Sans({
    subsets: [ 'latin' ],
    style: [ 'normal' ],
    variable: '--font-open-sans'
})

const proximaNova = localFont({
    src: '../public/fonts/proxima-nova-bold.otf',
    weight: '700',
    style: 'normal',
    variable: '--title-font'
})

const RootLayout = ({ children }) => (
    <html lang="en" className={`${openSans.variable} ${proximaNova.variable}`}>
        <body>
            <Header />
            <main>
                {children}
            </main>
            <Footer />
        </body>
    </html>
)

RootLayout.propTypes = {
    children: PropTypes.node.isRequired
}

export default RootLayout
